version: '3.8'
services:
  db:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nestjs
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nestjs
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"

volumes:
  postgres:
    name: nest-prisma-docker-db

networks:
  nestjs:
    driver: bridge
